version: 2.1

jobs: 
  build: 
    docker:
      - image: cimg/node:18.20
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo "${CIRCLE_BRANCH}"
      - restore_cache:
          keys: 
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache: 
          paths: 
            - node_modules
          key: app-{{ checksum "package.json" }}

  deploy-to-aws-s3:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/repo
    steps: 
      - checkout
      - run:
          name: Show current branch 
          command: echo "${CIRCLE_BRANCH}"
      - run: 
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "build successful"
      - run: 
          name: Deploy to AWS 3
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws --region "${AWS_REGION}" s3 sync ~/repo/build "s3://${AWS_PROD_BUCKET}" --delete
            elif [ "${CIRCLE_BRANCH}" = "staging" ]; then
              aws --region "${AWS_REGION}" s3 sync ~/repo/build "s3://${AWS_STAGING_BUCKET}" --delete
            else
              aws --region "${AWS_REGION}" s3 sync ~/repo/build "s3://${AWS_DEV_BUCKET}" --delete
            fi

  deploy-to-cloudfront:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/repo
    steps: 
      - checkout
      - run:
          name: Show current branch 
          command: echo "${CIRCLE_BRANCH}"
      - run: 
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "build successful"
      - run: 
          name: Deploy to AWS Cloudfront
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws cloudfront create-invalidation --distribution-id "${AWS_PROD_DISTRIBUTION_ID}" --paths '/*'
            elif [ "${CIRCLE_BRANCH}" = "staging" ]; then  
              aws cloudfront create-invalidation --distribution-id "${AWS_STAGING_DISTRIBUTION_ID}" --paths '/*'
            else
              aws cloudfront create-invalidation --distribution-id "${AWS_DEV_DISTRIBUTION_ID}" --paths '/*'
            fi

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws-s3:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
                - staging
      - deploy-to-cloudfront:
          requires:
            - deploy-to-aws-s3
          filters:
            branches:
              only:
                - develop
                - master
                - staging